/* FILENAME: UNITS.H
 * PROGRAMMER: OK2
 * PURPOSE: Globe project declaration module.
 * LAST UPDATE: 07.06.2014
 */

#ifndef __UNITS_H_
#define __UNITS_H_

#include "anim.h"

/* Функция создания объекта анимации */
ok2UNIT * OK2_CowUnitCreate( VOID );

/* Функция создания объекта анимации */
ok2UNIT * OK2_ClockUnitCreate( VOID );

/* Функция создания объекта анимации */
ok2UNIT * OK2_PhotoUnitCreate( VOID );

/* Функция создания информационного объекта анимации */
ok2UNIT * OK2_InfoUnitCreate( VOID );

/* Create coub function */
ok2UNIT * OK2_CubeUnitCreate( VOID );

#endif /* __UNITS_H_ */

/* END OF 'UNITS.H' FILE */
